# Generated by Django 3.2.6 on 2021-09-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=6, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('nomusu', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=10)),
                ('estado', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
